name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.27.3

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=$PWD/kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/namespace.yml
        kubectl apply -f kubernetes/deployment.yml
        kubectl apply -f kubernetes/service.yml
        kubectl apply -f kubernetes/wisecow-ingress.yml

